// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rakqutfgccsolruybhyh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJha3F1dGZnY2Nzb2xydXliaHloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2ODY3ODksImV4cCI6MjA2OTI2Mjc4OX0.7rPiveymaPtqna151_gzxalGE6ggQpUmD0KLuFPB4EM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});